### ISSUE TITLE
SQL error when searching on virtualField columns.

### ISSUE THREAD

**Issue by cnizzardini** [cnizzardini/cakephp-datatable#3]
When searching is performed on a virtualField a SQL error is encountered because SQL cannot find the field.

I am not sure how I want to address this problem at the moment. I certainly don't want to muddy the code with what could be a relatively edge scenario. 

Work Around:
For now in your DataTables aoColumns configuration set {bSearchable: false} on columns which are virtualFields. If you want to search on these fields put them in DataTables (the actual columns and not the virtualField) and in the configuration set {bVisible: false}.

**Comment by fr0z3nfyr** [comment]
Create the virtual field in your model constructor instead of in the controller action and the search will work normally. See issue #36 for more details.
